version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: restaurant-finder-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - restaurant-finder-network

networks:
  restaurant-finder-network:
    driver: bridge